services:
  love-generator:
    container_name: love-generator
    image: ghcr.io/oorbea/love-generator:latest
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - public-net

networks:
  public-net:
    external: true
